galaxy_info:
  author: Your Name
  description: A brief description of the role
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal
  categories:
    - system
    - cloud

dependencies: []
